@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/
Content-Type: {{contentType}}

###
POST http://{{host}}/login
Content-Type: {{contentType}}

{
    "username":"aofiee",
    "password":"password"
}

###
GET http://{{host}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjE4Nzg0OWYxLTc2NGMtNGZmMy05MTE3LWI4YmE0ZGEzZmY2NCIsImNvbnRleHQiOnsidXNlciI6ImFvZmllZTY2NkBnbWFpbC5jb20iLCJkaXNwbGF5X25hbWUiOiJLaG9ta3JpZCBMLiIsInJvbGVzIjpbImFkbWluIiwicmVwb3J0Il19LCJleHAiOjE2MjMyNDQxMTAsImlhdCI6MTYyMzI0MzIxMCwiaXNzIjoiRGlhYmxvcyIsInN1YiI6IjE0NDQ3OWJkLWZjZGMtNGM5Zi1iMTE2LWYyYTA4ODA3YTRjMyJ9.mkebxgcGQCNV0XvJVQ9aESvyR9uy0B2ffBFqLXUk3PM

###
DELETE  http://{{host}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjE4Nzg0OWYxLTc2NGMtNGZmMy05MTE3LWI4YmE0ZGEzZmY2NCIsImNvbnRleHQiOnsidXNlciI6ImFvZmllZTY2NkBnbWFpbC5jb20iLCJkaXNwbGF5X25hbWUiOiJLaG9ta3JpZCBMLiIsInJvbGVzIjpbImFkbWluIiwicmVwb3J0Il19LCJleHAiOjE2MjMyNDQxMTAsImlhdCI6MTYyMzI0MzIxMCwiaXNzIjoiRGlhYmxvcyIsInN1YiI6IjE0NDQ3OWJkLWZjZGMtNGM5Zi1iMTE2LWYyYTA4ODA3YTRjMyJ9.mkebxgcGQCNV0XvJVQ9aESvyR9uy0B2ffBFqLXUk3PM

###
POST http://{{host}}/refresh
Content-Type: application/x-www-form-urlencoded

refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0IjpudWxsLCJleHAiOjE2MjM4NDgwMTAsImlhdCI6MTYyMzI0MzIxMCwiaXNzIjoiRGlhYmxvcyIsInJlZnJlc2hfdXVpZCI6IjRiYTUxOGE4LTBkNzgtNDQwMS05YWVhLTk3NTQyNWI1ZTI2OSIsInN1YiI6IjE0NDQ3OWJkLWZjZGMtNGM5Zi1iMTE2LWYyYTA4ODA3YTRjMyJ9.yDsUp4gEv0GLhBkkG9ycxz-sDJHDJLEDijZoO3zQ4ik

###
POST http://{{host}}/refresh
Content-Type: {{contentType}}

{"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0IjpudWxsLCJleHAiOjE2MjM4NDgwMTAsImlhdCI6MTYyMzI0MzIxMCwiaXNzIjoiRGlhYmxvcyIsInJlZnJlc2hfdXVpZCI6IjRiYTUxOGE4LTBkNzgtNDQwMS05YWVhLTk3NTQyNWI1ZTI2OSIsInN1YiI6IjE0NDQ3OWJkLWZjZGMtNGM5Zi1iMTE2LWYyYTA4ODA3YTRjMyJ9.yDsUp4gEv0GLhBkkG9ycxz-sDJHDJLEDijZoO3zQ4ik"}