@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/
Content-Type: {{contentType}}

###
POST http://{{host}}/login
Content-Type: {{contentType}}

{
    "username":"aofiee",
    "password":"password"
}

###
GET http://{{host}}/profile
Authorization: Bearer 

###
DELETE  http://{{host}}/logout
Authorization: Bearer 

###
POST http://{{host}}/refresh
Content-Type: application/x-www-form-urlencoded

refresh_token=

###
POST http://{{host}}/refresh
Content-Type: {{contentType}}

{"refresh_token":""}
